[versions]

kotlinx-serialization = "1.9.0"

slf4j = "2.0.17"

ktor = "3.3.2"

[libraries]

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }


ktorClient-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClient-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClient-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktorClient-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorClient-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }


ktorSerialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

[plugins]
